In [14]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([0,2,4,8])

In [4]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [5]:
c = a[:,None] + b[None,:]

print(c)
c[:, 2]

[[ 1  3  5  9]
 [ 2  4  6 10]
 [ 3  5  7 11]]


array([5, 6, 7])

In [6]:
np.repeat(a[:,None],4,1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [7]:
(3,1) + (1,4) -> (3,4)

SyntaxError: invalid syntax (<ipython-input-7-9ea1007935ac>, line 1)

In [9]:
l = [[1, 2], [.5, 6]]
l.remove([1, 2])

In [10]:
l

[[0.5, 6]]

In [19]:
np.random.normal(loc=0, scale=1)


-0.44463613423604403